apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs1
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: pod1
      labels:
        app: nginx
    spec:
      containers:
        - name: container1
          image: nginx
          ports:
            - containerPort: 80
